// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function GetUsers(arg1, arg2) {
  return window['go']['main']['App']['GetUsers'](arg1, arg2);
}
