// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateUser(arg1:models.User):Promise<models.User>;

export function GetUsers(arg1:number,arg2:number):Promise<Array<models.User>>;
